import Image from "next/image"; import Link from "next/link"; import {Baby,BookOpen,GraduationCap,Music2,Sparkles,Users,Volume2,ArrowRight} from "lucide-react"; import {Button,Eyebrow,SectionHeading} from "@/components/ui"; import {ProgramCard,LocationCard} from "@/components/cards"; import {TrialFinder} from "@/components/trial-finder"; import {programs,locations,faqs,images} from "@/data/content"; import {businessServices} from "@/data/services"; import {siteConfig} from "@/config/site";
const audiences=[[Baby,"Early Learners","A joyful first encounter with sound, rhythm, and movement."],[Sparkles,"Children","Strong foundations shaped through play, curiosity, and steady progress."],[Music2,"Teens","Creative skills, growing independence, and music that feels personal."],[Users,"Adults","Begin something new or reconnect with the music you have missed."]];
const benefits=[[BookOpen,"Learning with direction","A clear path helps every new skill feel achievable."],[GraduationCap,"Guidance that listens","Teaching shaped around each learner’s pace and personality."],[Volume2,"Confidence on stage","Performance gives practice purpose and progress a moment to shine."],[Users,"Music at every age","A welcoming place for first notes, next steps, and fresh beginnings."]];
export default function Home(){return <>
<section className="hero"><div className="container hero-grid"><div><Eyebrow>Yamaha Music School</Eyebrow><h1>Music Starts Here.</h1><p className="hero-copy">From a child’s first note to a lifelong passion, find a place to learn, play, and grow.</p><div className="hero-actions"><Button href="/trial">Book a Trial Class</Button><Button href="/programs" variant="secondary">Explore Programs</Button></div><p className="trust-line"><span/>{siteConfig.tagline}</p></div><div className="hero-visual"><div className="hero-main"><Image src={images.hero} alt="Young musician learning in a warm music school setting" fill preload sizes="(max-width:768px) 100vw, 55vw"/></div><div className="hero-note"><strong>First notes. Big dreams.</strong><span>Learn · Play · Grow</span></div></div></div></section>
<section className="business-intro"><div className="container"><SectionHeading eyebrow="Beyond the lesson" title="Everything music, in one place." copy="From learning your first song to caring for the instrument you love, Max & Jeanny supports more of your musical journey."/><div className="business-grid">{businessServices.map((item,index)=><Link className="business-card" href={item.href} key={item.id}><span>0{index+1} · {item.verb}</span><h3>{item.title}</h3><p>{item.description}</p><ArrowRight/></Link>)}</div></div></section>
<section className="audience-section"><div className="container"><SectionHeading eyebrow="Find the right class" title="Find the right place to begin." copy="Every musical journey starts differently. Tell us who is learning and we’ll help you discover the right program."/><div className="audience-grid">{audiences.map(([Icon,title,copy])=>{const I=Icon as typeof Baby;return <article className="audience-card" key={title as string}><I/><span>{title as string}</span><p>{copy as string}</p></article>})}</div><div className="section-action align-left"><Button href="/programs">Find My Program</Button></div></div></section>
<section className="program-section"><div className="container"><SectionHeading eyebrow="Music school" title="Find an instrument that feels like you." copy="From playful first sounds to confident performance, choose a path that makes you want to keep playing."/><div className="program-grid editorial-programs">{programs.slice(0,4).map(p=><ProgramCard key={p.slug} program={p}/>)}</div><div className="helper-cta"><div><strong>Not sure which program is right?</strong><span>Tell us the student’s age and interests.</span></div><Button href="/trial" variant="secondary">Help Me Choose</Button></div></div></section>
<section className="why"><div className="container"><SectionHeading eyebrow="Why Max & Jeanny" title="Learn with joy. Grow with confidence." copy="Where thoughtful guidance, consistent practice, and the excitement of making music come together."/><div className="benefit-grid">{benefits.map(([Icon,title,copy])=>{const I=Icon as typeof BookOpen;return <article className="benefit" key={title as string}><I/><h3>{title as string}</h3><p>{copy as string}</p></article>})}</div></div></section>
<section className="quick-trial"><div className="container quick-trial-grid"><div><Eyebrow>Try a class</Eyebrow><h2>Your first class is one step away.</h2><p>Choose a few details and we’ll take you straight to your trial class request.</p></div><TrialFinder/></div></section>
<section className="locations"><div className="container"><SectionHeading eyebrow="Our locations" title="Music, closer to home." copy="Choose the Max & Jeanny branch that fits your family’s rhythm."/><div className="location-grid">{locations.map(l=><LocationCard key={l.id} location={l}/>)}</div></div></section>
<section className="experience"><div className="container"><SectionHeading eyebrow="Music for every stage" title="There is always a place to begin again."/><div className="gallery-grid">{[[images.children,"Early learners"],[images.teacher,"Growing musicians"],[images.performance,"Teens finding their sound"],[images.adult,"Adults making time for music"]].map(([src,label])=><div className="gallery-item" key={label}><Image src={src} alt={label} fill sizes="(max-width:768px) 100vw, 40vw"/><span>{label}</span></div>)}</div></div></section>
<section className="event-teaser"><div className="container event-teaser-grid"><div><Eyebrow>Music in the community</Eyebrow><h2>Music is meant to be shared.</h2><p>From student performances to musical activities, discover what’s happening at Max & Jeanny.</p></div><a href={siteConfig.social.instagram.url} target="_blank" rel="noreferrer">Follow {siteConfig.social.instagram.handle}<ArrowRight size={18}/></a></div></section>
<section className="faq"><div className="container faq-wrap"><SectionHeading eyebrow="Good to know" title="Questions before your first note?"/><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
<section className="final-cta"><div className="container"><h2>Make music part of your story.</h2><p>Your first lesson could be the beginning of something you’ll love for life.</p><Button href="/trial" variant="light">Book a Trial Class</Button></div></section>
</>}
